### ISSUE TITLE
start additional services before full mev components are launched

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/ethereum-package#168]
MEV requires epoch 1 and @barnabasbusa suggested we can launch additional services before waiting for this to happen. This makes sense to me.

**Comment by h4ck3rk3y** [comment]
@kamilchodola is on this!

**Comment by kamilchodola** [comment]
Just tested it once and seems to be working fine but need more tests

**Comment by h4ck3rk3y** [comment]
@kamilchodola i had to revert the previous change as it was causing issues with the mev-flood contracts being deployed.

**Comment by h4ck3rk3y** [comment]
MEV doesn't require epoch 1 so this isn't painful anymore, MEV starts at epoch 0. There were some problems with mev-flood init if we changed the ordering; closing this. Will open if people want the ordering to change
