### ISSUE TITLE
Change default number of nodes to 2

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/ethereum-package#200]

**Comment by leeederek** [comment]
@mieubrisse hello! Can you elaborate a bit on the reasoning & your use case behind this ask? This info will help us prioritize :) thank you!

**Comment by h4ck3rk3y** [comment]
I think this came up during the demo where @barnabasbusa noted that there are peering issues as there is no CL client to peer with!

**Comment by barnabasbusa** [comment]
yeah, single node can't peer with anything, so I think we should add a geth/teku node in the default config.

**Comment by barnabasbusa** [comment]
No reason to implement this actually. Prefer to leave it as it is currently.
