### ISSUE TITLE
Empty blocks when running mev networks without regular geth node

### ISSUE THREAD

**Issue by piwonskp** [kurtosis-tech/ethereum-package#201]
Hey, I'd like to run a network without a regular geth node. To do that I use the command:
```kurtosis run github.com/kurtosis-tech/eth2-package '{"mev_type": "full", "participants": []}'```

The network is created, however blocks generated by the network do not include any transactions. 

Why do the network generate empty blocks only?

**Comment by piwonskp** [comment]
It appears fuzzers use `eth_sendRawTransaction` method while builder supports only `eth_sendPrivateTransaction` and `eth_sendBundle`.

https://docs.flashbots.net/flashbots-protect/additional-documentation/eth-sendPrivateTransaction
https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint#eth_sendbundle

**Comment by piwonskp** [comment]
Sending transactions to builders work properly. I've just noticed that the problem with mev-flood is the fact that contract deploy transactions are included in blocks at 4th epoch, however the flood tries to spam transactions since 0 epoch. Thus the command crashes. There is no problem when a regular node is part of the network since it is including transactions in blocks since 0 epoch.

@h4ck3rk3y is there a way to delay the run of fuzzers? Starting fuzzers at 4th epoch would probably resolve the issue

**Comment by h4ck3rk3y** [comment]
@piwonskp I missed this message. Is this still an issue!?

https://github.com/kurtosis-tech/ethereum-package/blob/main/main.star#L217-L224

^ We wait for the capella fork epoch at the moment but we can move it to before the mev_flood spam in background to go with your logic in case capella fork epoch < 4
