### ISSUE TITLE
cleanup parsing further post merge of two packages

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/ethereum-package#229]
https://github.com/kurtosis-tech/eth2-package/pull/228#discussion_r1337332995

**Comment by h4ck3rk3y** [comment]
https://github.com/kurtosis-tech/eth2-package/pull/228#discussion_r1337339533

**Comment by h4ck3rk3y** [comment]
https://github.com/kurtosis-tech/eth2-package/pull/228#discussion_r1337365346

**Comment by barnabasbusa** [comment]
Some additional comments:
* Group all mev related tooling into `mev` directory
* Use local locators instead of absolute locators
* Fix: https://github.com/kurtosis-tech/eth-network-package/issues/118

**Comment by barnabasbusa** [comment]
@h4ck3rk3y we good to close this issue?
