### ISSUE TITLE
Add EIP-4788 contract deployment workflow

### ISSUE THREAD

**Issue by parithosh** [kurtosis-tech/ethereum-package#230]
EIP-4788 adds a contract that needs to be present. We used to do this by hardcoding the contract at genesis, but we'd like to move to a deployment approach (which is what mainnet will use as well). 

To do this:
- fund the address `0x0B799C86a49DEeb90402691F1041aa3AF2d3C875`
- send `eth_sendRawTransaction` with data `f8838085e8d4a510008303d0908080b86a60618060095f395ff33373fffffffffffffffffffffffffffffffffffffffe14604d57602036146024575f5ffd5b5f35801560495762001fff810690815414603c575f5ffd5b62001fff01545f5260205ff35b5f5ffd5b62001fff42064281555f359062001fff0155001b820539851b9b6eb1f0`

this should be done post genesis but pre-deneb. ideally done via starlark, but i guess its fine if we wrap it into a tiny docker image or something and add a sleep.

**Comment by h4ck3rk3y** [comment]
Done!
