### ISSUE TITLE
Consider merging beacon_metrics_gazer and light_beaconchain_explorer into single setting

### ISSUE THREAD

**Issue by kamilchodola** [kurtosis-tech/ethereum-package#240]
Noticed when playing around with additonal_services that once You will remove `beacon_metrics_gazer` and keep `light_beaconchain_explorer` it won't start properly. 

Would be nice to keep that under one setting to avoid confusion when reducing amount of container started

**Comment by barnabasbusa** [comment]
Hopefully next week I can begin working on https://github.com/kurtosis-tech/ethereum-package/issues/231 which will also resolve #140
