### ISSUE TITLE
[Feature] Allow to stop network at specific block

### ISSUE THREAD

**Issue by piwonskp** [kurtosis-tech/ethereum-package#258]
For benchmarking or any kind of activity that involves comparing networks it would be very handy to be able to specify a configuration that allows to stop the network. There may be multiple conditions on which the network may be stopped. 

The most useful conditions to stop the network as I see it:
* At a specific block number
* After a certain amount of time

Such network could then return the result by printing a report to stdout, saving in a file or keeping grafana container up so it's accessible.

**Comment by h4ck3rk3y** [comment]
Relevant discussion with Oleg - https://github.com/kurtosis-tech/kurtosis/issues/1474

Highly recommend using the SDK for this!
