### ISSUE TITLE
Update the Ethereum Kurtosis package to disable peer scoring

### ISSUE THREAD

**Issue by bsamuels453** [kurtosis-tech/ethereum-package#304]
cc @barnabasbusa 

https://github.com/crytic/attacknet/issues/6

We'll need peer scoring/banning disabled globally to prevent nodes impacted by faults from being permanently ejected from the network.

Lighthouse: --disable-peer-scoring

Lodestar: use flag disablePeerScoring

Teku: –Xp2p-gossip-scoring-enabled

Prysm: –disable-peer-score

Nimbus: –direct-peer (not entirely sure if it disables ALL peer scoring though)

https://discord.com/channels/595666850260713488/892088344438255616/1163511789946929202

**Comment by barnabasbusa** [comment]
Would you want to be able to enable/disable this flag per participant or global switch only?

**Comment by barnabasbusa** [comment]
correct flags:

Lighthouse: `--disable-peer-scoring`

Lodestar: `--disablePeerScoring`

Teku: `--Xp2p-gossip-scoring-enabled`

Prysm: `--disable-peer-scorer`

Github issue converts `--` to `–` which leads to a nasty bug if you try to use the github version of `–`.

In the future please always format the text in \` \`.

**Comment by barnabasbusa** [comment]
Heads up, prysm already disabled peer scoring if the peers are static peers. 
And currently we use `cmd.append("--peer=" + ctx.multiaddr)` (https://github.com/kurtosis-tech/ethereum-package/blob/main/src/cl/prysm/prysm_launcher.star#L297) for all peers.

**Comment by barnabasbusa** [comment]
Teku will also never disconnect from static peers.
