### ISSUE TITLE
EL Geth client stops when running MEV stack

### ISSUE THREAD

**Issue by avalonche** [kurtosis-tech/ethereum-package#306]
Running `ethpandaops/geth:lightclient-devnet-9-ae44519` and testing the MEV stack with:

```
kurtosis run . '{   "network_params": {
      "capella_fork_epoch": 0, "deneb_fork_epoch": 1
   },
   "mev_type": "full",
   "mev_params": {
        "mev_relay_image": "mev-boost-relay", "mev_builder_image": "builder"
   }}'
```

And the geth client often stops with no error logs. Sometimes see this on the builder EL client as well. The test still run fine but I have to manually start the EL client again.

OS: M1 Mac 13.2.1

cli-version: <= 0.84.7

**Comment by barnabasbusa** [comment]
Please reopen if the issuer persist.
