### ISSUE TITLE
error interpreting Starlark code 

### ISSUE THREAD

**Issue by lyfsn** [kurtosis-tech/ethereum-package#352]
Hello, is there something wrong with my operation, or is it some other problem?

```
/work/fsn/pos/kurtosis ❯ kurtosis version                           
CLI Version:   0.85.3

To see the engine version (provided it is running): kurtosis engine status
~/work/fsn/pos/kurtosis ❯ kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package "$(cat ./network_params.yaml)"

INFO[2023-11-06T19:39:17+08:00] No Kurtosis engine was found; attempting to start one... 
INFO[2023-11-06T19:39:17+08:00] Starting the centralized logs components...  
INFO[2023-11-06T19:39:17+08:00] Fetching image 'timberio/vector:0.31.0-debian' is running in 'missing' mode 
INFO[2023-11-06T19:39:17+08:00] Centralized logs components started.         
INFO[2023-11-06T19:39:17+08:00] Fetching image 'kurtosistech/engine:0.85.3' is running in 'missing' mode 
INFO[2023-11-06T19:39:17+08:00] Successfully started Kurtosis engine         
INFO[2023-11-06T19:39:17+08:00] Creating a new enclave for Starlark to run inside... 
INFO[2023-11-06T19:39:18+08:00] Enclave 'my-testnet' created successfully    
There was an error interpreting Starlark code 
Evaluation error: int: invalid literal with base 10: 
	at [github.com/kurtosis-tech/ethereum-package/main.star:83:55]: run
	at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:194:42]: launch_participant_network
	at [github.com/kurtosis-tech/ethereum-package/src/el/geth/geth_launcher.star:92:35]: launch
	at [0:0]: int

Error encountered running Starlark code.
INFO[2023-11-06T19:39:23+08:00] =================================================== 
INFO[2023-11-06T19:39:23+08:00] ||          Created enclave: my-testnet          || 
INFO[2023-11-06T19:39:23+08:00] =================================================== 
Name:            my-testnet
UUID:            b95a16abaae4
Status:          RUNNING
Creation Time:   Mon, 06 Nov 2023 19:39:17 CST

========================================= Files Artifacts =========================================
UUID           Name
9ab47b915564   task-7efd962d-4644-46fd-b304-f3cbca1ce9e0-python-script
5538e7661a0c   task-a85c2ff2-ef30-497f-ad0f-2d8a81e40526-python-script

========================================== User Services ==========================================
UUID   Name   Ports   Status
```

The `./network_params.yaml` same as https://github.com/kurtosis-tech/ethereum-package/blob/main/network_params.yaml

**Comment by wangyufsn** [comment]
By the way, how pass `--volume` params to the container?

**Comment by h4ck3rk3y** [comment]
Regarding `--volume` we don't allow for this fully just yet. I am curious abut your use case? What are you trying to do?!

**Comment by wangyufsn** [comment]
@h4ck3rk3y May I ask a few more questions? I haven't found direct answers in the documentation or configuration:

1. Is it possible to specify the external port exposed by geth, such as 8545:8545, whereas currently, it is a random port:8545?
2. Can a custom genesis.json file be used to start a geth client?

I look forward to your answer!

**Comment by h4ck3rk3y** [comment]
@wangyufsn  - feel free to ask questions!

1. Hey right now it isn't possible via this package to expose specific ports. We have an engineer working on a productized solution to allow users to export specific ports at specified ports. There's a workaround for this that we use in the near-package called `public_ports` but we want to deprecate that soon.
2. We use the [ethereum-genesis-generator](https://github.com/ethpandaops/ethereum-genesis-generator) to generate the genesis file and a lot of what goes into the generator can be configured via [parameters](https://github.com/kurtosis-tech/ethereum-package/blob/764b7dc0577a8e8da9dac3519d18db51720f2b4b/src/prelaunch_data_generator/el_cl_genesis/el_cl_genesis_generator.star#L81) but we don't support uploading a custom `genesis.json` just yet. I'd recommend creating a new ticket with this request and highlighting why you are trying to do this

**Comment by h4ck3rk3y** [comment]
@lyfsn We now support passing volumes as well. Closing this ticket!
