### ISSUE TITLE
Full beaconchain explorer not working with nethermind

### ISSUE THREAD

**Issue by piwonskp** [kurtosis-tech/ethereum-package#367]
When specifying nethermind as the first participant the full beaconchain explorer does not work.

Might be the client issue @kamilchodola

**Comment by barnabasbusa** [comment]
that sounds more like a full beaconchain sort of bug. @peterbitfly is beaconchain supposed to work with non geth/erigon ELs?

**Comment by h4ck3rk3y** [comment]
Can confirm that I have seen this as well; from experience

1. It requires the first client to be geth
2. https://github.com/kurtosis-tech/ethereum-package/blob/c558cb2eab25cc8c3718b1fda6759a0819e6f942/static_files/full-beaconchain-config/config.yaml.tmpl#L21C1-L22 here it takes geth/erigon url;
