### ISSUE TITLE
add support for blockscout

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/ethereum-package#372]

**Comment by franjoespejo** [comment]
Really important for us, specially if the https://docs.blockscout.com/for-users/verifying-a-smart-contract module is enabled

**Comment by barnabasbusa** [comment]
@franjoespejo would you consider contributing this tooling ?

**Comment by franjoespejo** [comment]
Thanks @barnabasbusa! would love but we cannot commit to it atm. We are arranging things to contribute very soon, would take this ticket if is still open

**Comment by igor-ritual** [comment]
Working rough draft: https://github.com/kurtosis-tech/ethereum-package/compare/main...igor-ritual:ethereum-package:blockscout

**Comment by barnabasbusa** [comment]
I'd recommend not having this package enabled by default, but make it an optionally configurable package. 

Feel free to open a PR when you feel like its ready for review.

**Comment by barnabasbusa** [comment]
Would you please add mem/cpu requests/limits to the application? Similar to https://github.com/kurtosis-tech/ethereum-package/pull/396

**Comment by barnabasbusa** [comment]
This is now merged with #481
