### ISSUE TITLE
Start permissioned devnet

### ISSUE THREAD

**Issue by gregdhill** [kurtosis-tech/ethereum-package#377]
I want to start a permissioned devnet with a strict set of validators defined at genesis. Is this possible? As I understand it, the default [deposit contract](https://github.com/ethereum/consensus-specs/blob/8fa1f8ed0a2315a4e5b0f08cf6e404202af45a5b/solidity_deposit_contract/deposit_contract.sol) would still allow anyone to stake ETH to become a validator. This is hard-coded [here](https://github.com/ethpandaops/ethereum-genesis-generator/blob/f9451c326977898bab6225c4c24bfa9da0e867a0/apps/el-gen/genesis_geth.py#L65) so I guess we would need to make this configurable to change the contract set at genesis.

**Comment by barnabasbusa** [comment]
Your kurtosis cluster is running on a private network, so others will not be able to connect to your RPC/Beacon endpoints to make deposits. 
Unless you expose your kurtosis cluster/docker network to the public internet, nobody is going to be able to make deposits to your private devnet. 

There are ways to create a permissioned devnet, but I think it'll be outside of the scope of kurtosis, as there seems to be no added benefit, but would add extra complexity. 

May I ask what is the usecase that you are facing?

**Comment by gregdhill** [comment]
Assuming that it is possible for other users to have funds, how can I setup the network so that no one can make deposits and join the validator set? Is it just the deposit contract that I need to change?

**Comment by barnabasbusa** [comment]
It has its own contract, its not using any of the public testnet/mainnet contract.

**Comment by gregdhill** [comment]
Yes I meant the deposit contract initialized at genesis on the devnet, that won't contain the deposits for the genesis validators right?

**Comment by barnabasbusa** [comment]
It does contain all the deposits, thats why you can make exits on a devnet too. The deposits are baked into the genesis state.

**Comment by parithosh** [comment]
The deposit contract state itself is "clean", there are no deposits in it from the EL perspective. The CL however requires a genesis.ssz (genesis state), we pre-load the validators in that state with this tool: https://github.com/protolambda/eth2-testnet-genesis/blob/master/validators.go#L50
