### ISSUE TITLE
Error validating Starlark code

### ISSUE THREAD

**Issue by igor-origin** [kurtosis-tech/ethereum-package#381]
Running `kurtosis run github.com/kurtosis-tech/ethereum-package` generates the following error:

https://gist.github.com/igor-origin/6d02bf2f14bb225c255072d69aa4c759

**Comment by barnabasbusa** [comment]
It looks like you have some very strict resource limitations on docker/kube. 

Each pod/container requires a certain amount of CPU from the system, if its not available, it won't be able to start. 

Could you clarify if you are running in kubernetes or docker? And how much resource do you have available?
