### ISSUE TITLE
Add easy way to sync private testnet or devnet

### ISSUE THREAD

**Issue by igor-ritual** [kurtosis-tech/ethereum-package#389]
Issue similar to https://github.com/kurtosis-tech/ethereum-package/issues/378

This issue involves running two enclaves:

- The primary genesis enclave follows the provided default network participant configuration.
- The secondary enclave would sync from the primary enclave and reuse the genesis information.

What considerations or challenges are involved?
Does this issue make sense?

**Comment by barnabasbusa** [comment]
#378 is going to enable anyone to quickly sync a public testnet/devnet. 

This issue is about syncing another kurtosis enclave? May I ask what is your use case?

**Comment by igor-ritual** [comment]
The use case is to run a private testnet/devnet. It appears #378 unblocks this requirement. The idea is to start one enclave with a single genesis node and other enclaves in different machines joining the new private testnet.

**Comment by barnabasbusa** [comment]
378 will not work for other kurtosis devnets. It will work for ethpandaops' organized devnets only.

**Comment by barnabasbusa** [comment]
Are we good to close this issue?
