### ISSUE TITLE
Add blobber to kurtosis

### ISSUE THREAD

**Issue by parithosh** [kurtosis-tech/ethereum-package#391]
This tool: https://github.com/marioevz/blobber/
its a MITM between BN and VC, just for lh/prysm/lodestar for now.

**Comment by barnabasbusa** [comment]
I can add it once we have some docs for blobber!

**Comment by barnabasbusa** [comment]
@parithosh could you pls add the config example that we were discussing yesterday?

**Comment by barnabasbusa** [comment]
If enabled, default will be blobber_params.

If `blobber_params` are `--cl=node-01-beacon-api` then it won't be just passthrough. 
So maybe we want to have `blobber_params` to be [] by default, and only use `blobber_extra_params`?
