### ISSUE TITLE
Add nimbus EL

### ISSUE THREAD

**Issue by parithosh** [kurtosis-tech/ethereum-package#393]
https://github.com/status-im/nimbus-eth1

Perhaps also interesting for the portal folks :D (tag away)

**Comment by bharath-123** [comment]
mind if i pick it up? always wanted to dig into nimbus eth1. seem like a great opportunity!

**Comment by parithosh** [comment]
Of course, if you feel like it :)
@barnabasbusa I think this issue is untouched right?

**Comment by barnabasbusa** [comment]
yes, I don't think it's been picked up by anyone

**Comment by barnabasbusa** [comment]
@bharath-123 got any progress report on this issue?

**Comment by bharath-123** [comment]
hey @barnabasbusa not a lot of luck as I didn't get the time. If anyone else is free they can pick it up :) Apologies for this
