### ISSUE TITLE
Add config to speed up validator discovery

### ISSUE THREAD

**Issue by icesfeathers** [kurtosis-tech/ethereum-package#432]
Add ETH1_FOLLOW_DISTANCE, EPOCHS_PER_ETH1_VOTING_PERIOD, etc. configurations that can speed up validator discovery

**Comment by barnabasbusa** [comment]
EPOCHS_PER_ETH1_VOTING_PERIOD can't be changed, as that is a preset, not a config variable. 

I'll open a PR about making ETH1_FOLLOW_DISTANCE configurable.
