### ISSUE TITLE
Add metadata tags for node ID

### ISSUE THREAD

**Issue by bsamuels453** [kurtosis-tech/ethereum-package#435]
right now each node implicitly has an id associated (ex: cl-1-lodestar-reth, el-1-reth-lodestar, etc). 

when attacknet creates a fault that impacts at the node-level, it has to create 3 sub-faults, one for el, one for cl, and sometimes one for validator. 

if we had a metadata tag show up in kubernetes to identify the node id, we could use it to identify these pods and create only one sub-fault

**Comment by barnabasbusa** [comment]
can you not do wildcard matching for the names? *-1-*-*?

**Comment by bsamuels453** [comment]
that's a good point. I found a way to do this in a way chaos-mesh will be cool with
