### ISSUE TITLE
Teku CL - `Unknown Option: ignore-weak-subjectivity-period-enabled`

### ISSUE THREAD

**Issue by maugzeth** [kurtosis-tech/ethereum-package#438]
### Description

Seems to be an issue with latest deployments of test network due to participant with the following CL client configuration.

```json
{
  "el_client_type": "reth",
  "el_client_image": "ghcr.io/paradigmxyz/reth",
  "cl_client_type": "teku",
  "cl_client_image": "consensys/teku:latest",
  "count": 1
}
```

The error is due to unknown option being passed in `ignore-weak-subjectivity-period-enabled`.

This prevents my network's `ethereum-package` enclave from reliably spinning up, also increases time to spin up significantly.

Full error logs:

```
2024-01-08 13:43:26 Unknown option: '--ignore-weak-subjectivity-period-enabled=true'
2024-01-08 13:43:26 
2024-01-08 13:43:26 To display full help:
2024-01-08 13:43:26 teku [COMMAND] --help
```

Seems like the origin of the error is within `teku_launcher` here:

https://github.com/kurtosis-tech/ethereum-package/blob/5584cc84c50ca9845c544810fb8331ec8fcdcbc8/src/cl/teku/teku_launcher.star#L336

Either removing this option due to deprecation from teku or updating it seems to be the way to go.

**Comment by barnabasbusa** [comment]
Could you please verify which version of "latest" image you have locally stored on your computer? 

Alternatively, you can run kurtosis with `--image-download always` flag, that way you will ensure to always fetch actually the latest image from dockerhub.

**Comment by maugzeth** [comment]
Seems like passing `--image-download always` fixed it.

Version that was being pulled and deployed my local machine was `23.11.0`.
