### ISSUE TITLE
kurtosis enclave dump on kubernetes should return files/artifacts/etc

### ISSUE THREAD

**Issue by parithosh** [kurtosis-tech/ethereum-package#480]
currently the enclave dump is quite barebones, would be nice if all the relevant files are in to make it easier to debug

**Comment by mieubrisse** [comment]
Hey @parithosh , this is a core Kurtosis feature so would you mind migrating it to https://github.com/kurtosis-tech/kurtosis ?

**Comment by mieubrisse** [comment]
(or linking)

**Comment by parithosh** [comment]
closing in favour of https://github.com/kurtosis-tech/kurtosis/issues/2108
