### ISSUE TITLE
Error encountered when running Ethereum package with default args

### ISSUE THREAD

**Issue by abhiyana** [kurtosis-tech/ethereum-package#499]
**Description**:

**Steps to Reproduce**:
1. Run the following command in the terminal:
   ```
   kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package
   ```

**Expected Behavior**:
The `kurtosis run` command should successfully create an enclave named `my-testnet` and execute the Ethereum package without encountering any errors.

**Actual Behavior**:
After running the command, the following error is encountered:
```
INFO[2024-02-22T16:04:53+05:30] Creating a new enclave for Starlark to run inside... 
INFO[2024-02-22T16:04:55+05:30] Enclave 'my-testnet' created successfully    
There was an error interpreting Starlark code 
Evaluation error: Cannot construct 'ServiceConfig' from the provided arguments.
    Caused by: ServiceConfig: unexpected keyword argument "node_selectors"
    at [github.com/kurtosis-tech/ethereum-package/main.star:90:55]: run
    at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:453:42]: launch_participant_network
    at [github.com/kurtosis-tech/ethereum-package/src/el/geth/geth_launcher.star:120:24]: launch
    at [github.com/kurtosis-tech/ethereum-package/src/el/geth/geth_launcher.star:360:25]: get_config
    at [0:0]: ServiceConfig

Error encountered running Starlark code.
```

**Additional Context**:
- Version of Kurtosis: 0.87.1
---

**Suggested Solution**:
Try removing the arguments `node_selectors` from [this line of code](https://github.com/kurtosis-tech/ethereum-package/blob/e48483a130ba227dafd0d0fd9ee66c6cecc3bfce/src/el/geth/geth_launcher.star#L380C1-L380C9). It seems that passing this argument might be causing the issue.

**Comment by barnabasbusa** [comment]
whats your engine version? Is it also 87.1? `kurtosis engine status`

**Comment by abhiyana** [comment]
Thank you for the update, I was already using version  0.87.1 of Kurtosis. It worked after restarting the system.
