### ISSUE TITLE
get_enode_for_node returns incorrect ip for reth nodes

### ISSUE THREAD

**Issue by corduroybera** [kurtosis-tech/ethereum-package#505]
When using [get_enode_for_node](https://github.com/kurtosis-tech/ethereum-package/blob/f9343a2914456196e1209336c426b6ad44958428/src/el/el_admin_node_info.star#L23) it's largely to get the bootnode addresses. However, when calling `admin_nodeInfo` in reth, it doesn't apply the `extip` that was set via the `--nat` flag. Instead, the returned address is always of the format `enode://[hash]@127.0.0.1:30303`

This means when running a reth-only network you end up with no peering because the bootnode IPs do not reference the proper private IPs in the enclave.

**Comment by barnabasbusa** [comment]
Good catch, however, I think this might be a reth bug, rather than a kurtosis bug.

**Comment by corduroybera** [comment]
@barnabasbusa yeah, I was wondering that. Wasn't sure if there was a spec definition for what IP it should return there.

**Comment by barnabasbusa** [comment]
https://github.com/paradigmxyz/reth/issues/6961

**Comment by barnabasbusa** [comment]
Fixed: https://github.com/paradigmxyz/reth/pull/7181

`ethpandaops/reth:main-0a803c4` or newer.
