### ISSUE TITLE
Faild to start blobscan-api

### ISSUE THREAD

**Issue by qymlyl** [kurtosis-tech/ethereum-package#550]
faild to start blobscan-api, the error is as follows:
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/7196598e-d0d1-45ca-9ead-05c3db5060be)

the default configuration used, services configuration is as follows:
```
additional_services:
  - assertoor
  - broadcaster
  - tx_spammer
  - blob_spammer
  - custom_flood
  - goomy_blob
  - el_forkmon
  - blockscout
  - beacon_metrics_gazer
  - dora
  - full_beaconchain_explorer
  - prometheus_grafana
  - blobscan
```

**Comment by qymlyl** [comment]
startup command is: `kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package`

**Comment by qymlyl** [comment]
setup command: `kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package --args-file network_params.yaml`

**Comment by PabloCastellano** [comment]
I can't reproduce this issue

**Comment by barnabasbusa** [comment]
I also wasn't able to reproduce. Please run your command with `--image-download always` flag, and that will ensure that you don't have some older image locally cached on your computer that might cause this error. 

Please reopen the issue if you face any further issues.

**Comment by qymlyl** [comment]
I keep getting this error on my personal laptop
