### ISSUE TITLE
Don't enforce pbss for geth

### ISSUE THREAD

**Issue by remoterami** [kurtosis-tech/ethereum-package#556]
Because of https://github.com/ethereum/go-ethereum/issues/29101#issuecomment-1966566704 (also [here](https://github.com/ethereum/go-ethereum/blob/master/eth/state_accessor.go#L184-L186)) I don't want to use pbss yet. It'd be fine as default of course, but when adding `--gcmode archive` to `el_extra_params`, geth can't start at all: `Fatal: Failed to register the Ethereum service: incompatible state scheme, stored: path, provided: hash`

**Comment by barnabasbusa** [comment]
https://github.com/kurtosis-tech/ethereum-package/pull/562
