### ISSUE TITLE
'/bin/sh' not found in 'alpine:3.17'

### ISSUE THREAD

**Issue by qymlyl** [kurtosis-tech/ethereum-package#592]
'/bin/sh' not found in 'alpine:3.17'
os: CentOS7
install command: sudo yum install kurtosis-cli
kurtosis-cli version: kurtosis-cli-0.89.3-1.x86_64
run command: kurtosis run --enclave l1_eth_testnet github.com/kurtosis-tech/ethereum-package --args-file network_params.yaml
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/139cd50b-499c-4ae2-9b84-035515ed7855)
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/7660b05d-09e5-4b19-a50c-e440176d2232)

**Comment by barnabasbusa** [comment]
Could you please use an enclave name that has no `_` chars in them? As thats not an allowed character.

**Comment by barnabasbusa** [comment]
Are you trying to use a private repository? https://github.com/kurtosis-tech/kurtosis/commit/2f0d638c688828de3eb781b11d696883807357ba Looks like this PR added functionality for you to login to github and access private repos. Did you use this ?

**Comment by qymlyl** [comment]
> 您能否使用`_`其中不含字符的飞地名称？因为那不是允许的角色。



> Could you please use an enclave name that has no `_` chars in them? As thats not an allowed character.

sorry, this is my mistake, really can't use '_'

**Comment by qymlyl** [comment]
> Are you trying to use a private repository? [kurtosis-tech/kurtosis@2f0d638](https://github.com/kurtosis-tech/kurtosis/commit/2f0d638c688828de3eb781b11d696883807357ba) Looks like this PR added functionality for you to login to github and access private repos. Did you use this ?

I am running "kurtosis github login' on the server, because it cannot jump to the browser and an error will be reported.

**Comment by barnabasbusa** [comment]
cc: @tedim52

**Comment by qymlyl** [comment]
> > Are you trying to use a private repository? [kurtosis-tech/kurtosis@2f0d638](https://github.com/kurtosis-tech/kurtosis/commit/2f0d638c688828de3eb781b11d696883807357ba) Looks like this PR added functionality for you to login to github and access private repos. Did you use this ?
> 
> I am running "kurtosis github login' on the server, because it cannot jump to the browser and an error will be reported.

this problem also occurs when running "kurtosis web login' on the server.

**Comment by qymlyl** [comment]
> kurtosis engine start --github-auth-token

i did that, but it still didn't work
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/d1319d5f-5931-4b3b-a579-ea1abcc75560)

**Comment by qymlyl** [comment]
I found the problem. There is alpine:3.17 in my docker image list. I deleted it and re-run it and it was successful.

**Comment by qymlyl** [comment]
thanks
