### ISSUE TITLE
Setting "github-auth-token" still prompts "kurtosis github login"

### ISSUE THREAD

**Issue by qymlyl** [kurtosis-tech/ethereum-package#596]
setting github-auth-token still prompts "kurtosis github login"
execution environment：server
os: CentOS7
kurtosis cli version: 0.89.3
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/816ca404-4aa0-43ec-ac72-01392907157f)

**Comment by qymlyl** [comment]
is there a way to download these packages for local use?

**Comment by qymlyl** [comment]
What if I want to use it on a private network (not connected to the Internet)

**Comment by qymlyl** [comment]
> setting github-auth-token still prompts "kurtosis github login" execution environment：server os: CentOS7 kurtosis cli version: 0.89.3 ![image](https://private-user-images.githubusercontent.com/61776278/328735851-816ca404-4aa0-43ec-ac72-01392907157f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzk1MDgsIm5iZiI6MTcxNTEzOTIwOCwicGF0aCI6Ii82MTc3NjI3OC8zMjg3MzU4NTEtODE2Y2E0MDQtNGFhMC00M2VjLWFjNzItMDEzOTI5MDcxNTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzMzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MzQ3ODdmMDQyYjQyNTJiMjQwM2VhMDMwMGZkYWQ3M2RkYzNkNTVhZTY5MDRmOTIyYTQ0MGU4MGU5YmM4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._soPSmon3vyvDU--3ARL9SSGAfdf-SFY1GWdJCtGpc4)

And this step sometimes succeeds and sometimes fails.

**Comment by qymlyl** [comment]
After the above steps are successful, the following error will appear，how to find the cause of this error
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/d5904122-fdc1-4baf-a913-8dfb32230223)

**Comment by qymlyl** [comment]
> After the above steps are successful, the following error will appear，how to find the cause of this error ![image](https://private-user-images.githubusercontent.com/61776278/328746299-d5904122-fdc1-4baf-a913-8dfb32230223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzk4OTMsIm5iZiI6MTcxNTEzOTU5MywicGF0aCI6Ii82MTc3NjI3OC8zMjg3NDYyOTktZDU5MDQxMjItZmRjMS00YmFmLWE5MTMtOGRmYjMyMjMwMjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzMzk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNmY1N2JiZTJlODUzMDIzOThkNjFkOWQzYzI5ODJhYTE2OGQ4NGY5MmE4NzczM2E3OTI0NTZiYzUzYjZhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVT4H8uHgA6MG240UxooontRGzFWNEWwl_n1cIVoIWg)

I have successfully created an enclave instance, but after deleting the enclave instance and recreating the enclave instance, this problem occurred.

**Comment by qymlyl** [comment]
> > After the above steps are successful, the following error will appear，how to find the cause of this error ![image](https://private-user-images.githubusercontent.com/61776278/328746299-d5904122-fdc1-4baf-a913-8dfb32230223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzk4OTMsIm5iZiI6MTcxNTEzOTU5MywicGF0aCI6Ii82MTc3NjI3OC8zMjg3NDYyOTktZDU5MDQxMjItZmRjMS00YmFmLWE5MTMtOGRmYjMyMjMwMjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzMzk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNmY1N2JiZTJlODUzMDIzOThkNjFkOWQzYzI5ODJhYTE2OGQ4NGY5MmE4NzczM2E3OTI0NTZiYzUzYjZhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVT4H8uHgA6MG240UxooontRGzFWNEWwl_n1cIVoIWg)
> 
> I have successfully created an enclave instance, but after deleting the enclave instance and recreating the enclave instance, this problem occurred.

restart the machine and run it again and the problem will disappear.
The first run was successful. I closed the firewall in order to access blobscan.
Then after the environment was deleted, the firewall was turned on (if it cannot run without the firewall, an error will be reported), and this problem occurred when running again.

**Comment by qymlyl** [comment]
However, the following problem will occur. This problem seems to be that the image 'ghcr.io/blockscout/smart-contract-verifier:v1.6.0' needs to be re-downloaded every time, but the image download is very slow and takes several hours.
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/39dbfee1-801a-4c76-8aa3-29625c94960c)

**Comment by qymlyl** [comment]
> However, the following problem will occur. This problem seems to be that the image 'ghcr.io/blockscout/smart-contract-verifier:v1.6.0' needs to be re-downloaded every time, but the image download is very slow and takes several hours. ![image](https://private-user-images.githubusercontent.com/61776278/328749400-39dbfee1-801a-4c76-8aa3-29625c94960c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDY0ODcsIm5iZiI6MTcxNTE0NjE4NywicGF0aCI6Ii82MTc3NjI3OC8zMjg3NDk0MDAtMzlkYmZlZTEtODAxYS00Yzc2LThhYTMtMjk2MjVjOTQ5NjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA1Mjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMmY2ZjgzY2RiY2RkNmVhM2I5ODI0ZDc0MWNhM2Y5N2Q0NWNjYWI0ZTg0MjFkNzk5Yjk4M2QzOGYyOWI4MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RSjBc0JRyDhXxpYOoKNxqnhX3QjH1LWeg93oTcvnXNo)

is there a way to download these files for local use?

**Comment by qymlyl** [comment]
I keep encountering the following problem, how to troubleshoot it?
![image](https://github.com/kurtosis-tech/ethereum-package/assets/61776278/f6cdc19e-5a25-4a8c-9f83-f4b7d4d68a31)

**Comment by qymlyl** [comment]
maybe it's a problem with my network，It may be a problem with my network. After I configure the proxy for the server, it can run normally.

**Comment by qymlyl** [comment]
Is there a way to download these packages for local use?
What if I want to use it on a private network (not connected to the Internet)

**Comment by barnabasbusa** [comment]
You could:
* pull all images ahead of the run, with docker pull command
* use a vpn
* sign up for another cloud provider, that is known to be working, and run your test there

**Comment by qymlyl** [comment]
> You could:
> 
> * pull all images ahead of the run, with docker pull command
> * use a vpn
> * sign up for another cloud provider, that is known to be working, and run your test there
> 
> could you join the kurtosis discord to discuss your issues? https://discord.gg/KWYkRCPN
> 
> github issues really isn’t meant to be used like this

yes, I wanted to ask you about the community chat group before， thanks

**Comment by qymlyl** [comment]
> setting github-auth-token still prompts "kurtosis github login" execution environment：server os: CentOS7 kurtosis cli version: 0.89.3 ![image](https://private-user-images.githubusercontent.com/61776278/328735851-816ca404-4aa0-43ec-ac72-01392907157f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA4NTQsIm5iZiI6MTcxNTE1MDU1NCwicGF0aCI6Ii82MTc3NjI3OC8zMjg3MzU4NTEtODE2Y2E0MDQtNGFhMC00M2VjLWFjNzItMDEzOTI5MDcxNTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2NDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjgxZDhlODUzNjYwNmU3MTJmY2QxZTgwODg3OGIxMDVkMmFiMzkxY2Y1ZjFhYjExNDZhYTA3NDZhZmJhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGvDaRKX4oHrJm91ugLzA5G9-fVVfp-2_r7kVQLVegQ)

but I have always encountered this problem
