### ISSUE TITLE
how should I config network_params to shadow fork holesky 

### ISSUE THREAD

**Issue by BlueShells** [kurtosis-tech/ethereum-package#609]
Hi 

i read the guide ,I am try to shadow fork holesky for my local test ,but I don't know where should I find these for holeksy 
network_params like 

deposit_contract_address , seconds_per_slot , num_validator_keys_per_node,  preregistered_validator_keys_mnemonic ,  and other config like network_sync_base_url 

or , the only param I need to change is to change
network: "kurtosis"  -> network: "holesky-shadowfork"

thanks

**Comment by barnabasbusa** [comment]
the only parameter you have do change is `network` yes.

**Comment by BlueShells** [comment]
@barnabasbusa thanks
